
version: "2"

run:
  timeout: 5m

linters:
  default: none
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - misspell
    - govet
  exclusions:
    paths:
      - ".*bindata.go$"
      - ".*pb.go"
      - ".*pb.gw.go"
    rules:
      - text: "not declared by package utf8"
        linters:
          - govet
      - path: "unicode/utf8/utf8.go"
        linters:
          - govet

formatters:
  enable:
    - gofmt
    - goimports