swagger: "2.0"
info:
  title: Sifter API
  description: API Load and status API
  version: 1.0.0
basePath: /api
paths:
  /playbook:
    post:
      summary: Starts loading a manifest
      description: Post a manifest to start loading into GRIP
      produces:
        - application/json
      consumes:
        - text/plain
        - application/x-www-form-urlencoded
      parameters:
        - in: body
          name: manifest
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
    get:
      summary: Get list of playbooks
      produces:
         - application/json
      responses:
        200:
          description: List of playbooks
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: Name of playbook
  /playbook/{id}:
    post:
      summary: Post a run request
      parameters:
        - in: path
          name: id
          type: string
          required: True
        - in: body
          name: params
          schema:
            type: string

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string



  /status:
    get:
      summary: Get Loading Status
      responses:
        '200':
          description: Status Data
          schema:
            type: object
            properties:
              current:
                type: string
                description: Current element being loaded
              stepNum:
                type: integer
                description: Current Step being loaded
              stepTotal:
                type: integer
                description: Total number of steps
              vertexCount:
                type: integer
                description: Number of vertices loaded so far
              edgeCount:
                type: integer
                description: Number of edges loaded so far
