// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPlaybookOKCode is the HTTP code returned for type GetPlaybookOK
const GetPlaybookOKCode int = 200

/*GetPlaybookOK List of playbooks

swagger:response getPlaybookOK
*/
type GetPlaybookOK struct {

	/*
	  In: Body
	*/
	Payload []*GetPlaybookOKBodyItems0 `json:"body,omitempty"`
}

// NewGetPlaybookOK creates GetPlaybookOK with default headers values
func NewGetPlaybookOK() *GetPlaybookOK {

	return &GetPlaybookOK{}
}

// WithPayload adds the payload to the get playbook o k response
func (o *GetPlaybookOK) WithPayload(payload []*GetPlaybookOKBodyItems0) *GetPlaybookOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get playbook o k response
func (o *GetPlaybookOK) SetPayload(payload []*GetPlaybookOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlaybookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetPlaybookOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
