// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostPlaybookIDOKCode is the HTTP code returned for type PostPlaybookIDOK
const PostPlaybookIDOKCode int = 200

/*PostPlaybookIDOK OK

swagger:response postPlaybookIdOK
*/
type PostPlaybookIDOK struct {

	/*
	  In: Body
	*/
	Payload *PostPlaybookIDOKBody `json:"body,omitempty"`
}

// NewPostPlaybookIDOK creates PostPlaybookIDOK with default headers values
func NewPostPlaybookIDOK() *PostPlaybookIDOK {

	return &PostPlaybookIDOK{}
}

// WithPayload adds the payload to the post playbook Id o k response
func (o *PostPlaybookIDOK) WithPayload(payload *PostPlaybookIDOKBody) *PostPlaybookIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post playbook Id o k response
func (o *PostPlaybookIDOK) SetPayload(payload *PostPlaybookIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPlaybookIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
