// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostManifestOKCode is the HTTP code returned for type PostManifestOK
const PostManifestOKCode int = 200

/*PostManifestOK OK

swagger:response postManifestOK
*/
type PostManifestOK struct {
}

// NewPostManifestOK creates PostManifestOK with default headers values
func NewPostManifestOK() *PostManifestOK {

	return &PostManifestOK{}
}

// WriteResponse to the client
func (o *PostManifestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
