// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostManifestHandlerFunc turns a function with the right signature into a post manifest handler
type PostManifestHandlerFunc func(PostManifestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostManifestHandlerFunc) Handle(params PostManifestParams) middleware.Responder {
	return fn(params)
}

// PostManifestHandler interface for that can handle valid post manifest params
type PostManifestHandler interface {
	Handle(PostManifestParams) middleware.Responder
}

// NewPostManifest creates a new http.Handler for the post manifest operation
func NewPostManifest(ctx *middleware.Context, handler PostManifestHandler) *PostManifest {
	return &PostManifest{Context: ctx, Handler: handler}
}

/*PostManifest swagger:route POST /manifest postManifest

Starts loading a manifest

Post a manifest to start loading into GRIP

*/
type PostManifest struct {
	Context *middleware.Context
	Handler PostManifestHandler
}

func (o *PostManifest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostManifestParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
