// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostPlaybookOKCode is the HTTP code returned for type PostPlaybookOK
const PostPlaybookOKCode int = 200

/*PostPlaybookOK OK

swagger:response postPlaybookOK
*/
type PostPlaybookOK struct {
}

// NewPostPlaybookOK creates PostPlaybookOK with default headers values
func NewPostPlaybookOK() *PostPlaybookOK {

	return &PostPlaybookOK{}
}

// WriteResponse to the client
func (o *PostPlaybookOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
