// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostPlaybookIDGraphOKCode is the HTTP code returned for type PostPlaybookIDGraphOK
const PostPlaybookIDGraphOKCode int = 200

/*PostPlaybookIDGraphOK OK

swagger:response postPlaybookIdGraphOK
*/
type PostPlaybookIDGraphOK struct {

	/*
	  In: Body
	*/
	Payload *PostPlaybookIDGraphOKBody `json:"body,omitempty"`
}

// NewPostPlaybookIDGraphOK creates PostPlaybookIDGraphOK with default headers values
func NewPostPlaybookIDGraphOK() *PostPlaybookIDGraphOK {

	return &PostPlaybookIDGraphOK{}
}

// WithPayload adds the payload to the post playbook Id graph o k response
func (o *PostPlaybookIDGraphOK) WithPayload(payload *PostPlaybookIDGraphOKBody) *PostPlaybookIDGraphOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post playbook Id graph o k response
func (o *PostPlaybookIDGraphOK) SetPayload(payload *PostPlaybookIDGraphOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPlaybookIDGraphOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
