// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sifter API
API Load and status API


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/x-www-form-urlencoded
    - text/plain

    Produces:
    - application/json

swagger:meta
*/
package restapi
