// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API Load and status API",
    "title": "Sifter API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/manifest": {
      "post": {
        "description": "Post a manifest to start loading into GRIP",
        "produces": [
          "application/json"
        ],
        "summary": "Starts loading a manifest",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API Load and status API",
    "title": "Sifter API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/manifest": {
      "post": {
        "description": "Post a manifest to start loading into GRIP",
        "produces": [
          "application/json"
        ],
        "summary": "Starts loading a manifest",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
}
