// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API Load and status API",
    "title": "Sifter API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/manifest": {
      "post": {
        "description": "Post a manifest to start loading into GRIP",
        "produces": [
          "application/json"
        ],
        "summary": "Starts loading a manifest",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/status": {
      "get": {
        "summary": "Get Loading Status",
        "responses": {
          "200": {
            "description": "Status Data",
            "schema": {
              "type": "object",
              "properties": {
                "current": {
                  "description": "Current element being loaded",
                  "type": "string"
                },
                "edgeCount": {
                  "description": "Number of edges loaded so far",
                  "type": "integer"
                },
                "stepNum": {
                  "description": "Current Step being loaded",
                  "type": "integer"
                },
                "stepTotal": {
                  "description": "Total number of steps",
                  "type": "integer"
                },
                "vertexCount": {
                  "description": "Number of vertices loaded so far",
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API Load and status API",
    "title": "Sifter API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/manifest": {
      "post": {
        "description": "Post a manifest to start loading into GRIP",
        "produces": [
          "application/json"
        ],
        "summary": "Starts loading a manifest",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/status": {
      "get": {
        "summary": "Get Loading Status",
        "responses": {
          "200": {
            "description": "Status Data",
            "schema": {
              "type": "object",
              "properties": {
                "current": {
                  "description": "Current element being loaded",
                  "type": "string"
                },
                "edgeCount": {
                  "description": "Number of edges loaded so far",
                  "type": "integer"
                },
                "stepNum": {
                  "description": "Current Step being loaded",
                  "type": "integer"
                },
                "stepTotal": {
                  "description": "Total number of steps",
                  "type": "integer"
                },
                "vertexCount": {
                  "description": "Number of vertices loaded so far",
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
