// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API Load and status API",
    "title": "Sifter API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/playbook": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get list of playbooks",
        "responses": {
          "200": {
            "description": "List of playbooks",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "Name of playbook",
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Post a manifest to start loading into GRIP",
        "consumes": [
          "text/plain",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Starts loading a manifest",
        "parameters": [
          {
            "name": "manifest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/playbook/{id}/{graph}": {
      "post": {
        "consumes": [
          "text/plain",
          "application/x-www-form-urlencoded"
        ],
        "summary": "Post a run request",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "graph",
            "in": "path",
            "required": true
          },
          {
            "name": "params",
            "in": "body",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/status": {
      "get": {
        "summary": "Get Loading Status",
        "responses": {
          "200": {
            "description": "Status Data",
            "schema": {
              "type": "object",
              "properties": {
                "current": {
                  "description": "Current element being loaded",
                  "type": "string"
                },
                "edgeCount": {
                  "description": "Number of edges loaded so far",
                  "type": "integer"
                },
                "stepNum": {
                  "description": "Current Step being loaded",
                  "type": "integer"
                },
                "stepTotal": {
                  "description": "Total number of steps",
                  "type": "integer"
                },
                "vertexCount": {
                  "description": "Number of vertices loaded so far",
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "API Load and status API",
    "title": "Sifter API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/playbook": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get list of playbooks",
        "responses": {
          "200": {
            "description": "List of playbooks",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "Name of playbook",
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Post a manifest to start loading into GRIP",
        "consumes": [
          "text/plain",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Starts loading a manifest",
        "parameters": [
          {
            "name": "manifest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/playbook/{id}/{graph}": {
      "post": {
        "consumes": [
          "text/plain",
          "application/x-www-form-urlencoded"
        ],
        "summary": "Post a run request",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "graph",
            "in": "path",
            "required": true
          },
          {
            "name": "params",
            "in": "body",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/status": {
      "get": {
        "summary": "Get Loading Status",
        "responses": {
          "200": {
            "description": "Status Data",
            "schema": {
              "type": "object",
              "properties": {
                "current": {
                  "description": "Current element being loaded",
                  "type": "string"
                },
                "edgeCount": {
                  "description": "Number of edges loaded so far",
                  "type": "integer"
                },
                "stepNum": {
                  "description": "Current Step being loaded",
                  "type": "integer"
                },
                "stepTotal": {
                  "description": "Total number of steps",
                  "type": "integer"
                },
                "vertexCount": {
                  "description": "Number of vertices loaded so far",
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
