
class: sifter
name: CBioPortal

config:
  tar: ""
  geneTable: ""
  schema: bmeg-dictionary/gdcdictionary/schemas

inputs:
  untar:
    plugin:
      commandLine: tar -xzf {{config.tar}}
  
  patientReader:
    tableLoad:
      input: data_clinical_patient.txt
  
  sampleReader:
    tableLoad:
      input: data_clinical_sample.txt

  rnaReader:
    transposeLoad:
      input: data_RNA_Seq_expression_median.txt
      rowSkip: 1

  mutationReader:
    tableLoad:
      input: data_mutations_extended.txt

pipelines:
  cases:
    - from: patientReader
    - project:
        mapping:
          id: "{{row.PATIENT_ID}}"
          submitter_id: "{{row.PATIENT_ID}}"
          type: "case"
          experiments:
            submitter_id: "TCGA"
    - objectValidate:
        title: Case
        schema: "{{config.schema}}"
    - emit:
        name: case

  samples:
    - from: sampleReader
    - project:
        mapping:
          id: "{{row.SAMPLE_ID}}"
          submitter_id: "{{row.SAMPLE_ID}}"
          cases:
            submitter_id: "{{row.PATIENT_ID}}"
          type: "sample"
    - objectValidate:
        title: Sample
        schema: "{{config.schema}}"
    - emit:
        name: sample

  aliquots:
    - from: sampleReader
    - project:
        mapping:
          id: "{{row.SAMPLE_ID}}-0000"
          submitter_id: "{{row.SAMPLE_ID}}-0000"
          samples:
            submitter_id: "{{row.SAMPLE_ID}}"
          type: "aliquot"
    - objectValidate:
        title: Aliquot
        schema: "{{config.schema}}"
    - emit:
        name: aliquot

  gene_expression:
    - from: rnaReader
    - project:
        mapping:
          id: "gexp:{{row.Entrez_Gene_Id}}"
          aliquot_id: "{{row.Entrez_Gene_Id}}-0000"
    - lookup:
        tsv:
          input: "{{config.geneTable}}"
        lookup: "{{row.Entrez_Gene_Id}}"
    - map:
        method: nodeMap
        python: |
          def nodeMap(x):
            values = {}
            for k, v in x.items():
              if k not in ["id", "aliquot_id", "Entrez_Gene_Id"]:
                values[k] = v
            return {
              "id": x["id"],
              "aliquot_id": x["aliquot_id"],
              "metric": "OTHER",
              "values": values
            }
    - emit:
        name: gene_expression

  mutations:
    - from: mutationReader
    - map:
        method: alleleID
        python: |
          import hashlib
          def alleleID(row):
            s = "GRCh37" + row["Chromosome"] + str(row["Start_Position"]) + str(row["End_Position"]) + row["Reference_Allele"] + row["Tumor_Seq_Allele1"]
            row["allele_id"] = "Allele:" + hashlib.sha1(s.encode()).hexdigest()
            return row
    - project:
        mapping:
          aliquot: "{{row.Tumor_Sample_Barcode}}-0000"
          ref: "{{row.Reference_Allele}}"
          alt: "{{row.Tumor_Seq_Allele1}}"
          ensembl_transcript: "{{row.Transcript_ID}}"
    - objectValidate:
        title: SomaticVariant
        schema: "{{config.schema}}"
    - emit:
        name: somatic_variant
    
  alleles:
    - from: mutationReader 
    - project:
        mapping:
          genome: "{{row.NCBI_Build}}"
          chromosome: "{{row.Chromosome}}"
          start: "{{row.Start_Position}}"
          end: "{{row.End_Position}}"
          strand: "{{row.Strand}}"
          reference_bases: "{{row.Reference_Allele}}"
          alternate_bases: "{{row.Tumor_Seq_Allele1}}"
          hugo_symbol: "{{row.Hugo_Symbol}}"
          effect: "{{row.Variant_Classification}}"
    - objectValidate:
        title: Allele
        schema: "{{config.schema}}"
    - emit:
        name: allele
