

class: sifter
name: GDCConvert

params:
  schema:
    type: path
    default: bmeg-dictionary/gdcdictionary/schemas

inputs:
  projects_scrape:
    plugin:
      commandLine: docker run --rm bmeg/sifter-gdc-scan /opt/gdc-scan.py projects
  cases_scrape:
    plugin:
      commandLine: docker run --rm bmeg/sifter-gdc-scan /opt/gdc-scan.py cases
  projects_data:
    jsonLoad:
      input: out.projects.json
  cases_data:
    jsonLoad:
      input: out.case.json

pipelines:
  projects:
    - from: projects_data
    - project:
        mapping:
          code: "{{row.project_id}}"
          programs: "{{row.program.name}}"
    - objectValidate:
        title: project
        schema: "{{params.schema}}"
    - emit:
        name: project
  
  experiments:
    - from: projects_data
    - project:
        mapping:
          code: "{{row.project_id}}"
          programs: "{{row.program.name}}"
          submitter_id: "{{row.program.name}}"
          projects: "{{row.project_id}}"
          type: experiment
    - objectValidate:
        title: experiment
        schema: "{{params.schema}}"
    - emit:
        name: experiment

  cases:
    - from: cases_data
    - project:
        mapping:
          studies: "{{row.project.project_id}}"
          experiments: "exp:{{row.project.project_id}}"
          type: case
    - objectValidate:
        title: case
        schema: "{{params.schema}}"
    - emit:
        name: case

  samples:
    - from: cases_data
    - fieldProcess:
        field: samples
    - project:
        mapping:
          type: sample
          id: "{{row.sample_id}}"
    - objectValidate:
        title: sample
        schema: "{{params.schema}}"
    - emit:
        name: sample

  aliquots:
    - from: cases_data
    - fieldProcess:
        field: samples
    - fieldProcess:
        field: portions
    - fieldProcess:
        field: analytes
    - fieldProcess:
        field: aliquots
    - project:
        mapping:
          type: aliquot
          id: "{{row.aliquot_id}}"
    - objectValidate:
        title: aliquot
        schema: "{{params.schema}}"
    - emit:
        name: aliquot
