
class: sifter
name: gene-table

params:
  geneTSV: ftp://ftp.ncbi.nih.gov/gene/DATA/gene2ensembl.gz

inputs:
  geneReader:
    tableLoad:
      input: "{{params.geneTSV}}"
      columns:
        - tax_id
        - GeneID
        - Ensembl_gene_identifier
        - RNA_nucleotide_accession.version
        - Ensembl_rna_identifier
        - protein_accession.version
        - Ensembl_protein_identifier

pipelines:
  transform:
    - from: geneReader
    - filter:
        field: tax_id
        match: "9606"
    - tableWrite:
        output: gene.table
        columns:
          - GeneID
          - Ensembl_gene_identifier
