
class: sifter
name: hugo-ensembl

params:
  hugoJSON: ftp://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/json/locus_types/gene_with_protein_product.json

inputs:
  hugoReader:
    jsonLoad:
      input: "{{params.hugoJSON}}"

pipelines:
  transform:
    - from: hugoReader
    - fieldProcess:
        field: response.docs
    - filter:
        field: ensembl_gene_id
        check: exists
    - tableWrite:
        output: hugo-ensembl.table
        columns:
          - symbol
          - ensembl_gene_id
