// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exec.proto

package evaluate

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Code struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Function             string   `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d737c7315c25422, []int{0}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Code) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

type CompileResult struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompileResult) Reset()         { *m = CompileResult{} }
func (m *CompileResult) String() string { return proto.CompactTextString(m) }
func (*CompileResult) ProtoMessage()    {}
func (*CompileResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d737c7315c25422, []int{1}
}

func (m *CompileResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileResult.Unmarshal(m, b)
}
func (m *CompileResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileResult.Marshal(b, m, deterministic)
}
func (m *CompileResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileResult.Merge(m, src)
}
func (m *CompileResult) XXX_Size() int {
	return xxx_messageInfo_CompileResult.Size(m)
}
func (m *CompileResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileResult.DiscardUnknown(m)
}

var xxx_messageInfo_CompileResult proto.InternalMessageInfo

func (m *CompileResult) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CompileResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Input struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d737c7315c25422, []int{2}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Input) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Result struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d737c7315c25422, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Code)(nil), "evaluate.Code")
	proto.RegisterType((*CompileResult)(nil), "evaluate.CompileResult")
	proto.RegisterType((*Input)(nil), "evaluate.Input")
	proto.RegisterType((*Result)(nil), "evaluate.Result")
}

func init() { proto.RegisterFile("exec.proto", fileDescriptor_4d737c7315c25422) }

var fileDescriptor_4d737c7315c25422 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x14, 0x74, 0x43, 0x77, 0xad, 0x0f, 0x76, 0x95, 0x87, 0xe0, 0xd2, 0x93, 0xe4, 0x24, 0x08, 0x15,
	0xd6, 0x8f, 0x3f, 0x50, 0x3c, 0x78, 0xed, 0x3f, 0x88, 0xc9, 0x13, 0x02, 0xd9, 0xbe, 0x12, 0x13,
	0xe9, 0xcf, 0x97, 0x66, 0xfb, 0x75, 0xe8, 0x6d, 0xe6, 0x31, 0x93, 0x99, 0x09, 0x00, 0x75, 0xa4,
	0xcb, 0xd6, 0x73, 0x60, 0xcc, 0xe9, 0x4f, 0xb9, 0xa8, 0x02, 0xc9, 0x0f, 0xc8, 0x2a, 0x36, 0x84,
	0x08, 0x99, 0x66, 0x43, 0xc7, 0xcd, 0xe3, 0xe6, 0xe9, 0xa6, 0x4e, 0x18, 0x0b, 0xc8, 0x7f, 0x62,
	0xa3, 0x83, 0xe5, 0xe6, 0x28, 0xd2, 0x7d, 0xe2, 0xf2, 0x1d, 0xf6, 0x15, 0x9f, 0x5b, 0xeb, 0xa8,
	0xa6, 0xdf, 0xe8, 0x02, 0x1e, 0x40, 0x58, 0x93, 0xec, 0xfb, 0x5a, 0x58, 0x83, 0xf7, 0xb0, 0x25,
	0xef, 0xd9, 0x0f, 0xce, 0x0b, 0x91, 0x2f, 0xb0, 0xfd, 0x6a, 0xda, 0x18, 0xfa, 0x3c, 0xa3, 0x82,
	0x1a, 0xf3, 0x7a, 0x3c, 0x75, 0x10, 0xe9, 0x91, 0x84, 0xe5, 0x09, 0x76, 0x43, 0xc0, 0x9a, 0x63,
	0x35, 0xe4, 0x74, 0x86, 0xfc, 0xb3, 0x23, 0x1d, 0x03, 0x7b, 0x7c, 0x83, 0xeb, 0xa1, 0x27, 0x1e,
	0xca, 0x71, 0x75, 0xd9, 0x4f, 0x2e, 0x1e, 0x96, 0x7c, 0x31, 0x45, 0x5e, 0xe1, 0x33, 0x64, 0x95,
	0x72, 0x0e, 0x6f, 0x67, 0x49, 0xaa, 0x5d, 0xdc, 0xcd, 0x87, 0x51, 0xfc, 0xbd, 0x4b, 0x7f, 0xfa,
	0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xf1, 0xeb, 0x24, 0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecutorClient is the client API for Executor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecutorClient interface {
	Compile(ctx context.Context, in *Code, opts ...grpc.CallOption) (*CompileResult, error)
	Call(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Result, error)
}

type executorClient struct {
	cc *grpc.ClientConn
}

func NewExecutorClient(cc *grpc.ClientConn) ExecutorClient {
	return &executorClient{cc}
}

func (c *executorClient) Compile(ctx context.Context, in *Code, opts ...grpc.CallOption) (*CompileResult, error) {
	out := new(CompileResult)
	err := c.cc.Invoke(ctx, "/evaluate.Executor/Compile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) Call(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/evaluate.Executor/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutorServer is the server API for Executor service.
type ExecutorServer interface {
	Compile(context.Context, *Code) (*CompileResult, error)
	Call(context.Context, *Input) (*Result, error)
}

// UnimplementedExecutorServer can be embedded to have forward compatible implementations.
type UnimplementedExecutorServer struct {
}

func (*UnimplementedExecutorServer) Compile(ctx context.Context, req *Code) (*CompileResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compile not implemented")
}
func (*UnimplementedExecutorServer) Call(ctx context.Context, req *Input) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterExecutorServer(s *grpc.Server, srv ExecutorServer) {
	s.RegisterService(&_Executor_serviceDesc, srv)
}

func _Executor_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Code)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evaluate.Executor/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).Compile(ctx, req.(*Code))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evaluate.Executor/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).Call(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _Executor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evaluate.Executor",
	HandlerType: (*ExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _Executor_Compile_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _Executor_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exec.proto",
}
