# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import exec_pb2 as exec__pb2


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compile = channel.unary_unary(
                '/evaluate.Executor/Compile',
                request_serializer=exec__pb2.Code.SerializeToString,
                response_deserializer=exec__pb2.CompileResult.FromString,
                )
        self.Call = channel.unary_unary(
                '/evaluate.Executor/Call',
                request_serializer=exec__pb2.Input.SerializeToString,
                response_deserializer=exec__pb2.Result.FromString,
                )


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Compile(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compile': grpc.unary_unary_rpc_method_handler(
                    servicer.Compile,
                    request_deserializer=exec__pb2.Code.FromString,
                    response_serializer=exec__pb2.CompileResult.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=exec__pb2.Input.FromString,
                    response_serializer=exec__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evaluate.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Compile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/evaluate.Executor/Compile',
            exec__pb2.Code.SerializeToString,
            exec__pb2.CompileResult.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/evaluate.Executor/Call',
            exec__pb2.Input.SerializeToString,
            exec__pb2.Result.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
