name: Go

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update pip
      run: pip install --upgrade pip

    - name: Python Dependencies for Conformance
      run: pip install requests grpcio-tools

    - name: Build
      run: go build -v ./

    - name: Test
      run: go test -v ./test/...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.1
          args:  --timeout 2m --disable-all -E gofmt 
