name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    #- name: Install required python libraries
    #  run: pip install -U grpcio-tools

    - name: Build
      run: go build -v ./

    - name: Test
      run: go test ./test
